### PR TITLE
Fixed job

### PR DESCRIPTION
**Pull request by sasa1977**
## Changes

This PR adds basic support for fixed scheduled jobs (e.g. run once a day at midnight). This addition is motivated by the needs in local_drive, where we're running a couple of hourly, daily, and weekly jobs.

The new job scheduler is the minimal abstraction which handles our needs and which is testable. The interface makes it easy to test that the job is executed at the desired time and that it produces desired side-effects.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by zvlasic** [comment]
Is there a commit or PR on LocalDrive which uses this, for documentation purposes?

**Comment by sasa1977** [comment]
> Is there a commit or PR on LocalDrive which uses this, for documentation purposes?

Yes. See [here](https://github.com/VeryBigThings/localdrive-backend/commit/e49a27afaaf06afe3e98d0164d7cf200d8253d10) and [here](https://github.com/VeryBigThings/localdrive-backend/commit/81bd04daf675c21b71201c9ae905a22755c5dc48).

**Comment by neektza** [comment]
@sasa1977 does this make Quantum scheduler obsolete?

**Comment by sasa1977** [comment]
> does this make Quantum scheduler obsolete?

It does. If you find in practice that something is missing let me know.

**Pull request merged**
