### PR TITLE
mailer helper

### PR DESCRIPTION
**Pull request by sasa1977**
## Changes

This PR introduces a small helper for sending e-mails, which can help us reduce a bit of boilerplate. Most notably, the helper allows us to use only one module (without it we need three - mailer, composer, and phoenix view).

You can see example usage in [this commit](https://github.com/VeryBigThings/banmed_wfm_backend/commit/b0efd5ade5826248d9bf372c868ec4640edbfaa5). Also take a look at docs [here](https://github.com/VeryBigThings/elixir_common/blob/6eb5e44a6b8f442c9b7df1d277746756065e24a0/lib/vbt/mailer.ex#L2-L51).

Mailer currently supports only basic fields (sender, single recipient, subject, body). Other features, such as multiple recipients, cc, attachments, are not supported, but it shouldn't be too hard to extend the code.

Finally, this mailer always sends the mail immediately via `deliver_now`. The default implementation of `deliver_later` is too naive, since it only provides "at most once" guarantees. My plan is to add proper support for "at least once" guarantees next.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by space-measurer — APPROVED** [review]
I have no objection.

**Review by tdebus — APPROVED** [review]
Cool, we'll test the usage on Gost, as we don't have many emails to rewrite, and have a very simple HTML template for one email.

Also, update to the `assert_delivered_email` breaks previous usage (see the [PR](https://github.com/VeryBigThings/gost_platform/pull/44) fixing it on GOST) - this is trivial now, but maybe we can develop best practices around this sample issue - changelog, referencing releases?

Another thing - Bamboo has a peculiar internal representation for email recipient and sender addresses - see a sample email matched using the helper:
```
%Bamboo.Email{
  assigns: :assigns_removed_for_testing,
  attachments: [],
  bcc: [],
  cc: [],
  from: {nil, "admin_local@gost.com"},
  headers: %{},
  html_body: "Hi John Smith 1,\n\n    You have been invited as a operator for Nautilus-3 on GOST Specter.\n\n\n    Please set up your password by clicking on <a href=\"http://localhost:3449/#!set-password/f0700ba5-7ee7-461a-a292-c66c46c1e2ca\">this link</a>.",
  private: %{},
  subject: "Welcome to GOST Specter",
  text_body: "Hi John Smith 1,\n\n    You have been invited as a operator for Nautilus-3 on GOST Specter.\n\n\n    Please set up your password by clicking on this link:\n    http://localhost:3449/#!set-password/f0700ba5-7ee7-461a-a292-c66c46c1e2ca",
  to: [nil: "john.smith.1@vbt.com"]
}
```
This means you have to match like this: `email = TestHelper.assert_delivered_email(to: [nil: ^user_email])`, which always surprises newcomers - maybe we can add to the documentation to contain an example like this? Also one using caret operator, which is the second mind-blowing moment I had with Ken, when he assigned to a new variable by accident :) 

I volunteer to write these docs in a new PR, if I am not missing something.

**Comment by sasa1977** [comment]
> Also, update to the `assert_delivered_email` breaks previous usage (see the [PR](https://github.com/VeryBigThings/gost_platform/pull/44) fixing it on GOST) - this is trivial now, but maybe we can develop best practices around this sample issue - changelog, referencing releases?

Good point! We should definitely think about keeping some changelog for breaking changes. The only reason I didn't add it now is because the previous behaviour was accidental, and not an intended design.

> Also one using caret operator, which is the second mind-blowing moment I had with Ken, when he assigned to a new variable by accident :)

Thanks for pointing it out. I'll see about expanding docs.

> This means you have to match like this: `email = TestHelper.assert_delivered_email(to: [nil: ^user_email])`, which always surprises newcomer

I could try to add some smartness which implicitly converts `to: [^user_email]` into `to: [{_, ^user_email}]`. WDYT?

**Comment by sasa1977** [comment]
> I could try to add some smartness which implicitly converts `to: [^user_email]` into `to: [{_, ^user_email}]`. WDYT?

Actually, on second thought, better not. This will lead to some other strange edge cases, so let's leave it like it is.

**Review by zvlasic — APPROVED** [review]

**Pull request merged**
